Bug fix in signup and profile and posting image functionality
Developers-codz/shareArts pull request #12
Opened 2022-06-13 02:52 UTC by Developers-codz

2022-06-13 07:49 UTC, vishalg8454 requested changes
2 bugs i noticed

- Unable to edit own posts from profile page
- No option for text only posts, image is necessary. This is not good experience.

2022-06-14 06:51 UTC, Developers-codz commented
> 2 bugs i noticed
> 
> * Unable to edit own posts from profile page
> * No option for text only posts, image is necessary. This is not good experience.

Hey, thanks for noticing those, I have fixed the first bug and for the second one its not a bug I took reference from Instagram and there we can't post without image that's why

2022-06-14 10:31 UTC, vishal804 approved these changes
Code Looks Clean

2022-06-14 10:31 UTC, vishal804 commented on src/Redux/Reducers/authSlice.js
> +        return response.data;
Console.log can be removed

2022-06-14 15:46 UTC, merged